title: The Mental Blog
theme: jekyll-theme-architect
description:
  Drew McCormack is the developer behind agenda.com, studiesapp.com, and ensembles.io
footer-links:
  twitter: drewmccormack
url: https://mentalfaculty.github.io
twitter_username: drewmccormack
baseurl: "/blog"
permalink: /:title/

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
 
