title: macanics
name: macanics
theme: jekyll-theme-architect
description:
  Dev blog of Drew McCormack, developer of agenda.com, studiesapp.com, and ensembles.io.
footer-links:
  twitter: drewmccormack
twitter_username: drewmccormack
permalink: /:title/
